### PR TITLE
Organizes folders a little better, adds ZenHub workaround.

### PR DESCRIPTION
**Pull request by spaulaus**
## Description
I reorganized the project into what I think are more logical folders. I'm sure that this structure will change over time but this is a good start.
### Folder Summary
* acquisition  -> Modules used for data acquisition tasks
    * produce_from_binary
* analysis -> Modules used for data analysis
    * binary_data_reader -> Program that reads from binary data formats
    * pixie_data_consumer -> Program that consumes from a Kafka topic
    * postges-plots -> Simple scripts to test connection / plotting from postgres
* constants -> Files that hold information about constants
* data_formats -> Modules related to binary data formats
    * ldf -> ORNL list mode data format
    * pld -> UTK experimental data format
* doc -> To hold documentation (does not exist yet since it's empty)
* hardware -> To hold files related to specific hardware
    * xia
        * pixie16

I plan for the hardware folder to expand and manage the analog hardware as well. I expect we'll end up with a CAEN folder too. I don't think we'll have much to stuff into the data_formats folder other than some decoders. I really don't intend for us to include writing any binary data formats. Reading them is still useful though. I removed the Kafka folder since those files were all for specific purposes. 

I also updated the issue and PR templates so that they are compatible with ZenHub. The HTML comments are not supported (yet) by ZenHub. This also future proofs us should we decide to move to a different PM platform in the future that doesn't support the HTML comments. 
## Related Issue
* #14 
* #11 
## Motivation and Context
As the project grows we need to ensure that we have a solid foundation to grow from. My original folder structure was ad-hoc and not suited for growth. 

The poor formatting of the issues on ZenHub made the platform completely useless to us. . 

## How Has This Been Tested?
I've ensured that all the programs run properly, but didn't do any other testing. These initial scripts will most definitely be reworked as we start to grow. 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [Contributing](https://github.com/spaulaus/dolosse/blob/master/.github/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by caswellp** [comment]
The kafka folder isn't mentioned in the folder summary.

**Comment by spaulaus** [comment]
The Kafka folder shouldn't exist anymore.

**Comment by LindsD** [comment]
> The Kafka folder shouldn't exist anymore.

I still see it.

**Comment by LindsD** [comment]
All looks in keeping with the structure given above. One suggestion though: Even though "doc" is empty, the folder can still exist now. I don't see why not.

**Pull request merged**
